
RECORDING_START_MARKER = "RecordingStart"
RECORDING_END_MARKER = "RecordingEnd"

CALIBRATION_START_MARKER = "CalibrationStart"
CALIBRATION_END_MARKER = "CalibrationEnd"

NEW_IMAGE_START_MARKER = "NewImageStart"
NEW_IMAGE_END_MARKER = "NewImageEnd"

FACE_IMAGE_MARKER = "Face"
LANDSCAPE_IMAGE_MARKER = "Landscape"

CROSS_START_MARKER = "CrossStart"
CROSS_END_MARKER = "CrossEnd"